language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:  
  - SIC_AFIP_ENV="testing" BUCKET_NAME="" AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY="" AWS_DEFAULT_REGION="" MAIL_USERNAME="globotest@yopmail.com" MAIL_PASSWORD=""
