language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:  
  - SIC_AFIP_ENV="testing" SIC_MAIL_ENV="testing" RECAPTCHA_SECRET_KEY="" RECAPTCHA_TEST_KEY="111111" export CLOUDINARY_URL="cloudinary://*:*-*@*"

addons:
  sonarcloud:
    organization: "globo-technology"
script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
