on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '14'    
    - uses: actions/checkout@v2
      with:        
        fetch-depth: 0
    - name: Build with Maven
      run: mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=globo-technology -Dsonar.projectKey=sic-api:sic-api
      env: 
        SIC_AFIP_ENV: "testing"
        SIC_MAIL_ENV: "testing"
        SIC_MAIL_USERNAME: ""
        SIC_MAIL_PASSWORD: ""
        RECAPTCHA_SECRET_KEY: ""
        RECAPTCHA_TEST_KEY: "111111"
        CLOUDINARY_URL: "cloudinary://*:*-*@*"
        SIC_CLOUDINARY_ENV: "testing"
        SIC_MERCADOPAGO_ACCESS_TOKEN: ""
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
